project_name: "run-tasks"

manager:
  encoding: null
  pattern_file_job_command: "{project_name}_job{job_id}_run{job_run_id}"
  storage_period:
    task_run_in_days: 100

notification:
  base_url: "http://127.0.0.1:5510"

  email:
    host: "smtp.mail.ru"
    port: 465
    send_to: "ilya.petrash@inbox.ru"
    login: "ilya.petrash@inbox.ru"
    password: "<password>"

  telegram:
    add_notify_url: "http://127.0.0.1:10016/add_notify"

web:
  host: "0.0.0.0"
  port: 5510
  debug: false
  secret_key: "<your-secret-key>"
  login: "<login>"
  password: "<password>"
